---
title: "Central Park Squirrels"
output: rmarkdown::github_document
---

# Can we Pinpoint Squirrel Behaviour to Specific Regions of Central Park?

```{r}

library(dplyr)

# Reading in the data

squirrel_data <- read.csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv", stringsAsFactors = F)

convertField <- function(data, field){
  data[which(grepl('false',squirrel_data[,field])),field] = 0
  data[which(grepl('true',squirrel_data[,field])),field] = 1
  data[,field] <- as.numeric(data[,field])
  return(data)
}

# Converting fields of interest to 1 and 0

squirrel_data <- convertField(squirrel_data,"Kuks")
squirrel_data <- convertField(squirrel_data,"Quaas")
squirrel_data <- convertField(squirrel_data,"Moans")
squirrel_data <- convertField(squirrel_data,"Tail.flags")
squirrel_data <- convertField(squirrel_data,"Tail.twitches")
squirrel_data <- convertField(squirrel_data,"Approaches")
squirrel_data <- convertField(squirrel_data,"Indifferent")
squirrel_data <- convertField(squirrel_data,"Runs.from")

# Accumulate scores for similar behaviour

squirrel_data$Scared <- rowSums(squirrel_data[,c("Kuks","Quaas","Moans","Tail.flags","Runs.from")])
squirrel_data$Curious <- rowSums(squirrel_data[,c("Tail.twitches","Approaches")]) + abs(squirrel_data$Indifferent - 1)
squirrel_data$Brave <- rowSums(squirrel_data[,c("Tail.twitches","Approaches")]) + abs(squirrel_data$Runs.from - 1)

knitr::kable(head(squirrel_data) %>% select(-Color.notes))

# Group squirrels by hectare, normalizing the behaviour metrics and averaging the coordinates

library(pillar)
options(pillar.sigfig = 10)

normalize <- function(x){
  return((x - min(x, na.rm = T)) / (max(x, na.rm = T) + 0.0000001 - min(x, na.rm = T)))
}

squirrel_data_grouped_data <- squirrel_data %>% summarise(Hectare = Hectare, norm_scared = normalize(Scared), norm_curious = normalize(Curious), norm_brave = normalize(Brave)) %>% group_by(Hectare) %>% summarize(scared_avg = mean(norm_scared), curious_avg = mean(norm_curious), brave_avg = mean(norm_brave))
squirrel_data_grouped_coords <- squirrel_data %>% group_by(Hectare) %>% summarize(X_avg = mean(X), Y_avg = mean(Y))
squirrel_data_grouped_count <- squirrel_data %>% group_by(Hectare)%>% tally()
squirrel_data_grouped <- left_join(squirrel_data_grouped_data, squirrel_data_grouped_coords, by = "Hectare") %>% left_join(squirrel_data_grouped_count, by = "Hectare")

knitr::kable(head(squirrel_data_grouped))
```

```{r}

library(ggplot2)
library(reshape2)

sorted_scared <- squirrel_data_grouped$scared_avg[order(squirrel_data_grouped$scared_avg)]
sorted_curious <- squirrel_data_grouped$curious_avg[order(squirrel_data_grouped$curious_avg)]
sorted_brave <- squirrel_data_grouped$brave_avg[order(squirrel_data_grouped$brave_avg)]
index = 1:length(sorted_brave)

sorted_data <- data.frame(index,sorted_scared,sorted_curious,sorted_brave)

ggplot(melt(sorted_data, id = "index"), aes(x=index, y = value, color = variable)) + geom_line()

```

```{r fig.height=16, fig.width=10}

library(ggmap)
library(grid)
library(gridExtra)
#park.map <- get_map(c(left = min(squirrel_data$X)-0.001, bottom = min(squirrel_data$Y)-0.001, right = max(squirrel_data$X)+0.001, top = max(squirrel_data$Y)+0.001))
#save(park.map, file = "park.map.Robj")
load(file="park.map.Robj")

p1 <- ggmap(park.map) + 
  geom_point(data = squirrel_data_grouped, aes(x = X_avg, y = Y_avg, color = n)) + 
  ggtitle("Number of Squirrels Recorded per Hectare") + 
  theme(plot.title = element_text(hjust = 0.5), plot.margin = unit(c(0,0,0,0),"cm"))

p2 <- ggmap(park.map) + 
  geom_point(data = squirrel_data_grouped, aes(x = X_avg, y = Y_avg, color = scared_avg)) + 
  ggtitle("Average Scared Score per Hectare") + 
  theme(plot.title = element_text(hjust = 0.5), plot.margin = unit(c(0,0,0,0),"cm"))

p3 <- ggmap(park.map) + 
  geom_point(data = squirrel_data_grouped, aes(x = X_avg, y = Y_avg, color = curious_avg)) + 
  ggtitle("Average Curiosity Score per Hectare") + 
  theme(plot.title = element_text(hjust = 0.5), plot.margin = unit(c(0,0,0,0),"cm"))

p4 <- ggmap(park.map) + 
  geom_point(data = squirrel_data_grouped, aes(x = X_avg, y = Y_avg, color = brave_avg)) + 
  ggtitle("Average Bravery Score per Hectare") + 
  theme(plot.title = element_text(hjust = 0.5), plot.margin = unit(c(0,0,0,0),"cm"))

grid.arrange(p1, p2, p3, p4, ncol = 2)

```

